/-
Copyright (c) 2025 SGC Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: SGC Formalization Team

# Impulsive Control: Thermodynamic Spiking

This module formalizes the **optimal control problem** for maintaining a valid
effective theory over time. The key insight: when effective theories have finite
validity horizons (T* = 1/ε), the optimal strategy is **impulsive control**—
discrete resets (spikes) rather than continuous adjustments.

## Physical Motivation

An effective theory (coarse-grained model) accumulates error over time:
- **Continuous dissipation**: Running an imperfect model generates heat/error
- **Validity horizon**: After time T* = 1/ε, the model becomes unreliable

The system has two choices:
1. **Continuous control**: Constantly fight the error (expensive, inefficient)
2. **Impulsive control**: Let error accumulate, then reset (spike)

**Claim**: Impulsive control is optimal. This is the physics of "when to think."

## The Thermodynamic Action

The total cost (Action) of a control policy π over horizon [0,T] is:

    S[π] = 𝔼[ ∫₀ᵀ |Defect(t)|² dt + λ · N_spikes ]

where:
- First term: Continuous dissipation (running cost of imperfect prediction)
- Second term: Discrete work (cost of renormalization/reset)
- λ: Spike cost parameter (metabolic cost of "thinking")

## Main Result (Conjectured)

The optimal policy is a **threshold policy**: Fire (spike) when |Defect(t)| ≥ θ*.

The optimal threshold θ* minimizes the average Action per cycle:
    θ* = argmin [ (θ²·τ(θ) + λ) / τ(θ) ]

where τ(θ) is the expected first-passage time to threshold θ.

## Connection to Neuroscience

This formalizes the "spiking neuron" as a thermodynamic regulator:
- **Membrane potential** ↔ Accumulated defect
- **Firing threshold** ↔ Optimal reset point θ*
- **Action potential** ↔ Renormalization spike (reset to valid model)
- **Refractory period** ↔ Post-spike validity window

## References

- Friston (2019): Free energy principle
- Rao & Ballard (1999): Predictive coding
- SGC Observables.ValidityHorizon: Finite horizon T* = 1/ε
- SGC Thermodynamics.DoobMeyer: Martingale decomposition

## Design Philosophy

Following SGC constraints:
1. **Discrete time** - Align with DoobMeyer framework
2. **Fintype state space** - Explicit sums, no measure theory
3. **Axiom transparency** - Optimization claims are explicit axioms/conjectures
-/

import SGC.Observables.ValidityHorizon
import SGC.Observables.EnergyUnification
import SGC.Thermodynamics.DoobMeyer

noncomputable section

namespace SGC.Control

open Finset Matrix Real SGC.Observables SGC SGC.Approximate SGC.Spectral

variable {V : Type*} [Fintype V] [DecidableEq V] [Nontrivial V]

/-! ## 1. Impulse Policy: When to Reset -/

/-- An **Impulse Policy** is a decision rule that determines when to "fire" (reset).

    In discrete time, this is a function from time and accumulated state to {0, 1}:
    - 0 = continue running the effective theory
    - 1 = fire (reset/renormalize)

    **Physical interpretation**: The policy encodes "when should the system think?"
    A value of 1 means "the accumulated error is too high; reset the model."

    **Stopping time interpretation**: The first time the policy outputs 1 is a
    stopping time with respect to the natural filtration. -/
structure ImpulsePolicy (V : Type*) where
  fire : ℕ → (V → ℝ) → Bool

/-- A **Threshold Policy** fires when the defect exceeds a threshold.

    This is the conjectured optimal form: fire when |Defect| ≥ θ. -/
def ThresholdPolicy (θ : ℝ) (L : Matrix V V ℝ) (P : Partition V)
    (pi_dist : V → ℝ) (hπ : ∀ v, 0 < pi_dist v) : ImpulsePolicy V where
  fire := fun _ _state =>
    let defect := opNorm_pi pi_dist hπ (DefectOperator L P pi_dist hπ)
    defect ≥ θ

/-- The **null policy** never fires. Represents "never reset."

    This is suboptimal: the effective theory eventually becomes invalid. -/
def NullPolicy : ImpulsePolicy V where
  fire := fun _ _ => false

/-- The **always policy** fires every step. Represents "continuous control."

    This is suboptimal: too much spike cost without benefit. -/
def AlwaysPolicy : ImpulsePolicy V where
  fire := fun _ _ => true

/-! ## 2. Thermodynamic Action: The Cost Functional -/

/-- **Running Cost**: The instantaneous cost of prediction error.

    At each time step, the system pays a cost proportional to |Defect|².
    This is the "heat" generated by running an imperfect model. -/
def RunningCost (L : Matrix V V ℝ) (P : Partition V) (pi_dist : V → ℝ)
    (hπ : ∀ v, 0 < pi_dist v) : ℝ :=
  DefectNormSquared L P pi_dist hπ

/-- **Spike Cost**: The fixed cost of performing a reset/renormalization.

    Parameter λ > 0 represents the metabolic cost of "thinking."
    - High λ: Spikes are expensive → fire less often → tolerate more error
    - Low λ: Spikes are cheap → fire more often → maintain low error -/
def SpikeCost (spikeCost : ℝ) (fired : Bool) : ℝ :=
  if fired then spikeCost else 0

/-- **Thermodynamic Action** over a finite horizon [0, T].

    S[π] = Σₜ₌₀ᵀ⁻¹ [ RunningCost(t) + SpikeCost(t) ]

    This is the total cost of operating under policy π.
    The optimal policy minimizes this action.

    **Note**: This is the discrete-time analog of the path integral:
    S[π] = ∫₀ᵀ |Defect(t)|² dt + λ · N_spikes -/
def ThermodynamicAction (L : Matrix V V ℝ) (P : Partition V) (pi_dist : V → ℝ)
    (hπ : ∀ v, 0 < pi_dist v) (spikeCost : ℝ) (policy : ImpulsePolicy V)
    (trajectory : ℕ → V → ℝ) (T : ℕ) : ℝ :=
  ∑ t ∈ Finset.range T,
    (RunningCost L P pi_dist hπ + SpikeCost spikeCost (policy.fire t (trajectory t)))

/-- **Average Action Rate**: Action per unit time.

    For ergodic analysis, we care about the long-run average:
    ρ[π] = lim_{T→∞} S[π] / T

    A policy is optimal if it minimizes this rate. -/
def AverageActionRate (L : Matrix V V ℝ) (P : Partition V) (pi_dist : V → ℝ)
    (hπ : ∀ v, 0 < pi_dist v) (spikeCost : ℝ) (policy : ImpulsePolicy V)
    (trajectory : ℕ → V → ℝ) (T : ℕ) : ℝ :=
  ThermodynamicAction L P pi_dist hπ spikeCost policy trajectory T / T

/-! ## 3. First Passage Time: When Does Defect Hit Threshold? -/

/-- **First Passage Time** to threshold θ.

    τ(θ) = inf { t : |Defect(t)| ≥ θ }

    For a threshold policy, this is the time between spikes.
    The optimal threshold balances:
    - Waiting longer (larger τ) → more accumulated running cost
    - Waiting shorter (smaller τ) → more frequent spike costs -/
def FirstPassageTime (θ : ℝ) (defect_trajectory : ℕ → ℝ) : ℕ :=
  Nat.find (⟨0, by simp⟩ : ∃ n, n = 0 ∨ |defect_trajectory n| ≥ θ)

/-- **Expected First Passage Time** (parametric).

    𝔼[τ(θ)] depends on the dynamics of the defect process.
    For Brownian-like defect growth: 𝔼[τ(θ)] ~ θ²/σ²

    This is axiomatized since proving it requires stochastic calculus. -/
axiom expected_first_passage_time (θ σ : ℝ) (hθ : 0 < θ) (hσ : 0 < σ) :
  ∃ τ_mean : ℝ, τ_mean > 0 ∧ τ_mean = θ^2 / σ^2

/-! ## 4. The Optimal Threshold Conjecture -/

/-- **Cycle Cost**: Total cost per spike-to-spike cycle.

    For a threshold policy with threshold θ:
    - Running cost accumulates: ∫₀^τ |Defect(t)|² dt ≈ (θ²/3) · τ
    - Plus one spike cost: λ

    Total cycle cost: C(θ) = (θ²/3) · τ(θ) + λ -/
def CycleCost (θ τ spikeCost : ℝ) : ℝ :=
  (θ^2 / 3) * τ + spikeCost

/-- **Average Rate for Threshold Policy**:

    ρ(θ) = CycleCost(θ) / τ(θ) = θ²/3 + λ/τ(θ)

    Minimizing ρ(θ) gives the optimal threshold. -/
def ThresholdAverageRate (θ τ spikeCost : ℝ) : ℝ :=
  CycleCost θ τ spikeCost / τ

/-- **Optimal Threshold** (Structure Definition).

    θ* is optimal if it minimizes the average action rate among all threshold policies.

    **Conjecture**: θ* = (3λσ²)^(1/4) where σ² is the defect diffusion rate.

    This structure packages the claim that a specific θ is optimal. -/
structure IsOptimalThreshold (θ : ℝ) (spikeCost σ : ℝ) : Prop where
  threshold_pos : 0 < θ
  spike_cost_pos : 0 < spikeCost
  diffusion_pos : 0 < σ
  minimizes_rate : ∀ θ' : ℝ, 0 < θ' →
    let τ := θ^2 / σ^2
    let τ' := θ'^2 / σ^2
    ThresholdAverageRate θ τ spikeCost ≤ ThresholdAverageRate θ' τ' spikeCost

/-- **Optimal Threshold Formula** (Axiom/Conjecture).

    The optimal firing threshold is:
        θ* = (3λσ²)^(1/4)

    **Derivation** (informal):
    - Average rate: ρ(θ) = θ²/3 + λσ²/θ²
    - Set dρ/dθ = 0: 2θ/3 - 2λσ²/θ³ = 0
    - Solve: θ⁴ = 3λσ², so θ* = (3λσ²)^(1/4)

    **Physical interpretation**:
    - High spike cost λ → higher threshold → fire less often
    - High diffusion σ → lower threshold → fire before defect grows too large -/
axiom optimal_threshold_formula (spikeCost σ : ℝ)
    (hsc : 0 < spikeCost) (hσ : 0 < σ) :
    let θ_star := (3 * spikeCost * σ^2) ^ (1/4 : ℝ)
    IsOptimalThreshold θ_star spikeCost σ

/-! ## 5. Threshold Optimality: Main Structural Result -/

/-- **Threshold Policies are Optimal** (Axiom).

    Among all impulse policies, threshold policies minimize the average action rate.

    **Why this is deep**: This is an instance of the general principle that
    optimal stopping problems with monotone payoffs have threshold solutions.
    The formal proof requires:
    - Hamilton-Jacobi-Bellman equation
    - Verification theorem for optimal stopping
    - Convexity of the value function

    We axiomatize this structural result. -/
axiom threshold_policy_optimal (L : Matrix V V ℝ) (P : Partition V)
    (pi_dist : V → ℝ) (hπ : ∀ v, 0 < pi_dist v) (spikeCost : ℝ) (hsc : 0 < spikeCost) :
    ∃ θ : ℝ, θ > 0 ∧ ∀ (policy : ImpulsePolicy V) (trajectory : ℕ → V → ℝ) (T : ℕ),
    AverageActionRate L P pi_dist hπ spikeCost (ThresholdPolicy θ L P pi_dist hπ) trajectory T ≤
    AverageActionRate L P pi_dist hπ spikeCost policy trajectory T

/-! ## 6. Connection to Validity Horizon -/

/-- **Validity Horizon as Threshold**.

    The validity horizon T* = 1/ε provides a natural threshold:
    when t > T*, the effective theory is invalid.

    **Claim**: The optimal threshold θ* corresponds to firing before T*. -/
def ValidityThreshold (ε : ℝ) (hε : 0 < ε) : ℝ := 1 / ε

/-- **Threshold-Horizon Consistency**.

    For the optimal threshold policy, the expected first passage time
    equals the validity horizon: 𝔼[τ(θ*)] ≈ T* = 1/ε.

    This connects control theory back to the Observables pillar. -/
axiom threshold_horizon_consistency (ε spikeCost σ : ℝ)
    (hε : 0 < ε) (hsc : 0 < spikeCost) (hσ : 0 < σ) :
    let θ_star := (3 * spikeCost * σ^2) ^ (1/4 : ℝ)
    let τ_star := θ_star^2 / σ^2
    ∃ C : ℝ, C > 0 ∧ |τ_star - 1/ε| ≤ C * (spikeCost * σ^2)^(1/2 : ℝ)

/-! ## 7. Non-Reversible Extension: When to Leave Equilibrium -/

/-- **Reversibility Detector**.

    The system may need to spike precisely when it drifts out of the reversible sector.
    A "reversibility defect" measures departure from self-adjointness.

    ‖L - L†‖_π measures non-normality.

    **Conjecture**: Optimal spikes occur when reversibility defect exceeds threshold. -/
def ReversibilityDefect (L : Matrix V V ℝ) (pi_dist : V → ℝ) : ℝ :=
  ∑ v, ∑ w, pi_dist v * |L v w - L w v * (pi_dist w / pi_dist v)|

/-- **Fire on Non-Reversibility** policy.

    This policy fires when the system becomes "too non-reversible."
    Relevant for systems that should maintain detailed balance. -/
def NonReversibilityPolicy (θ_rev : ℝ) (L : Matrix V V ℝ) (pi_dist : V → ℝ)
    (hπ : ∀ v, 0 < pi_dist v) : ImpulsePolicy V where
  fire := fun _ _ =>
    ReversibilityDefect L pi_dist ≥ θ_rev

/-! ## 8. Physical Interpretation: The Spiking Neuron -/

/-- **Thermodynamic Neuron** bundles the key parameters.

    A neuron is characterized by:
    - `threshold`: Firing threshold θ*
    - `spike_cost`: Metabolic cost λ of generating an action potential
    - `diffusion`: Rate σ at which membrane potential fluctuates
    - `reset_value`: Post-spike membrane potential (typically 0) -/
structure ThermodynamicNeuron where
  threshold : ℝ
  spike_cost : ℝ
  diffusion : ℝ
  reset_value : ℝ
  threshold_pos : 0 < threshold
  spike_cost_pos : 0 < spike_cost
  diffusion_pos : 0 < diffusion

/-- **Neuron fires optimally** if its threshold equals the optimal threshold.

    This is the central claim: biological neurons are thermodynamic regulators
    that minimize the action (free energy) via optimal threshold spiking. -/
def NeuronIsOptimal (n : ThermodynamicNeuron) : Prop :=
  n.threshold = (3 * n.spike_cost * n.diffusion^2) ^ (1/4 : ℝ)

/-- **Optimal Neuron Construction**.

    Given spike cost λ and diffusion σ, construct the optimal neuron. -/
def optimalNeuron (spikeCost σ : ℝ) (hsc : 0 < spikeCost) (hσ : 0 < σ) :
    ThermodynamicNeuron where
  threshold := (3 * spikeCost * σ^2) ^ (1/4 : ℝ)
  spike_cost := spikeCost
  diffusion := σ
  reset_value := 0
  threshold_pos := by
    apply Real.rpow_pos_of_pos
    apply mul_pos
    apply mul_pos
    · linarith
    · exact hsc
    · exact sq_pos_of_pos hσ
  spike_cost_pos := hsc
  diffusion_pos := hσ

theorem optimal_neuron_is_optimal (spikeCost σ : ℝ) (hsc : 0 < spikeCost) (hσ : 0 < σ) :
    NeuronIsOptimal (optimalNeuron spikeCost σ hsc hσ) := by
  unfold NeuronIsOptimal optimalNeuron
  rfl

end SGC.Control
